FROM node:18-alpine

WORKDIR /app

RUN apk add --no-cache netcat-openbsd

COPY package*.json ./
COPY tsconfig*.json ./
COPY nest-cli.json ./

RUN npm ci

COPY . .

RUN mkdir -p /app/logs

EXPOSE 4000

CMD ["npm", "run", "start:dev"]